# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Bird\'L' do
  pod 'JSQMessagesViewController'
  pod 'RFQuiltLayout'
end

target 'Bird\'LTests' do

end

